export const Filters = {
  Names: {
    emotion: 'emotion',
    anger: 'anger',
    contempt: 'contempt',
    disgust: 'disgust',
    fear: 'fear',
    happiness: 'happiness',
    neutral: 'neutral',
    sadness: 'sadness',
    surprise: 'surprise',
    bald: 'bald',
    hairColor: 'hairColor',
    makeup: 'makeup',
    eyemakeup: 'eyemakeup',
    lipmakeup: 'lipmakeup',
    glasses: 'glasses',
    accessories: 'accessories',
    gender: 'gender',
    age: 'age',
    smile: 'smile',
    headWear: 'headWear',
    mask: 'mask',
  },
  Types: {
    emotion: 'radio',
    anger: 'percentage',
    contempt: 'percentage',
    disgust: 'percentage',
    fear: 'percentage',
    happiness: 'percentage',
    neutral: 'percentage',
    sadness: 'percentage',
    surprise: 'percentage',
    bald: 'percentage',
    hairColor: 'Select',
    moustache: 'moustache',
    beard: 'beard',
    sideburns: 'sideburns',
    makeup: 'check',
    eyemakeup: 'bool',
    lipmakeup: 'bool',
    glasses: 'bool',
    accessories: 'check',
    gender: 'bool',
    age: 'integer',
    smile: 'percentage',
  },
  Default: {
    emotion: '',
    anger: false,
    contempt: false,
    disgust: false,
    fear: false,
    happiness: false,
    neutral: false,
    sadness: false,
    surprise: false,
    bald: false,
    hairColor: '',
    moustache: false,
    beard: false,
    sideburns: false,
    makeup: {
      eyemakeup: false,
      lipmakeup: false,
    },
    glasses: false,
    accessories: {
      headWear: false,
      glasses: false,
      mask: false,
    },
    gender: null,
    age: [0, 100],
    smile: false,
  },
  Emotions: {
    // emotion: 'emotion',
    anger: 'anger',
    contempt: 'contempt',
    disgust: 'disgust',
    fear: 'fear',
    happiness: 'happiness',
    neutral: 'neutral',
    sadness: 'sadness',
    surprise: 'surprise',
  },
  EmotionTitles: {
    emotion: 'Emotion',
    anger: 'Anger',
    contempt: 'Contempt',
    disgust: 'Disgust',
    fear: 'Fear',
    happiness: 'Happiness',
    neutral: 'Neutral',
    sadness: 'Sadness',
    surprise: 'Surprise',
  },
  Appearance: {
    eyemakeup: 'eyemakeup',
    lipmakeup: 'lipmakeup',
    moustache: 'moustache',
    beard: 'beard',
    sideburns: 'sideburns',
    bald: 'bald',
    hairColor: 'hairColor',
  },
  Other: {
    accessories: 'accessories',
    smile: 'smile',
    gender: 'gender',
    glasses: 'glasses',
    age: 'age',
    date: 'date',
    people: 'people',
  },
  Accessories: {
    headWear: 'headWear',
    glasses: 'glasses',
    mask: 'mask',
  },
  AccessoriesTitles: {
    headWear: 'Headwear',
    glasses: 'Glasses',
    mask: 'Mask',
  },
};
